import tkinter as tk
from tkinter import ttk
def calculating():
    uravnenye = uravnenye_entry.get()
    parts = uravnenye.split('+')
    c = int(parts[-1].split('=')[-1].strip())
    a = int(parts[0].replace('x^2', ''))
    b = int(parts[1].replace('x', ''))
    D = (b ** 2) - (4 * a * c)
    root1 = (-b + (D ** 0.5)) / (2 * a)
    root2 = (-b - (D ** 0.5)) / (2 * a)
    result_label.config(text=f'Корень 1: {root1}\nКорень 2: {root2}')
root = tk.Tk()
root.title('Решение квадратных уравнений')
root.geometry('500x500')
label = ttk.Label(root, text='Введите квадратное уравнение в формате ax^2 + bx + c = 0: ')
label.pack(pady=10)
uravnenye_entry = tk.Entry(root)
uravnenye_entry.pack(pady=10)
label_result = ttk.Label(root, text='Ответ:')
label_result.pack(pady=10)
result_label = tk.Label(root, text="")
result_label.pack()
buttont = ttk.Button(root, text="Вычислить", command=calculating)
buttont.pack(pady=10)
root.mainloop()